name: Release

on: workflow_dispatch

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          semantic_version: 19.0.2
          branch: main
          extends: |
            @rweich/semantic-release-config
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Outputs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo release version: ${{ steps.semantic.outputs.new_release_version }}
