name: Release

on: workflow_dispatch

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # 3.1.0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@8f6ceb9d5aae5578b1dcda6af00008235204e7fa # 3.2
        id: semantic
        with:
          semantic_version: 19.0.2
          branch: main
          extends: |
            @rweich/semantic-release-config
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Outputs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo release version: ${{ steps.semantic.outputs.new_release_version }}
