name: Run-Tests

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x, 19.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # 3.1.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # 3.5.1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install

      - run: yarn test
