name: Test-Release

on:
  pull_request:
    types: [ labeled ]
jobs:
  release:

    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'to-be-released')

    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install
      - name: Release Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: yarn semantic-release --dry-run --branches ${{ steps.branch-name.outputs.current_branch }}
