name: Test-Release

on:
  push:
  pull_request:

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        uses: tj-actions/branch-names@v5
        id: branch-name

      - name: Checkout
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          dry_run: true
          semantic_version: 19.0.2
          branch: ${{ steps.branch-name.outputs.current_branch }}
          extends: |
            @rweich/semantic-release-config@^2.0.6
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Test Outputs
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo release version: ${{ steps.semantic.outputs.new_release_version }}
